/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package canaryprism.littlethings;


public class Main {
    public static void main(String[] args) {
        //this is j
    }
}
