/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package canaryprism.littlethings;


public class Main {
    public static void main(String[] args) {
        //WIP
        canaryprism.littlethings.arraylist.AnArray.of(Object.class, 3, "", true);
    }
}
